// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.1
//   protoc               v7.35.1
// source: wmlhub/v1/hub.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Certificate, Challenge, Role } from "./identity.gen";

export const protobufPackage = "wmlhub.v1";

/** How the hub treats an envelope: whether it is retained, and what happens when a subscriber falls behind. */
export enum Kind {
  KIND_UNSPECIFIED = 0,
  /** KIND_SESSION_EVENTS - Published, retained in a ring, never dropped. A subscriber that falls behind is disconnected and resyncs. */
  KIND_SESSION_EVENTS = 1,
  /** KIND_TELEMETRY - Published, retained in a ring. Coalesced by `coalesce` and, past a limit, dropped with a Gap. */
  KIND_TELEMETRY = 2,
  /** KIND_COMMAND - Direct, not retained, never dropped. Offline recipient: Error{UNAVAILABLE} to the sender. */
  KIND_COMMAND = 3,
  /** KIND_COMMAND_RESULT - Direct, the answer to a command; as KIND_COMMAND. */
  KIND_COMMAND_RESULT = 4,
  /**
   * KIND_BULK - Direct, not retained: a large object in chunks (a screenshot). Counts toward the recipient's queue like any
   * direct envelope.
   */
  KIND_BULK = 5,
  UNRECOGNIZED = -1,
}

/** One unit on the wire. The first Frame a connection sends is Hello; the hub answers Welcome or Error and closes. */
export interface Frame {
  hello?: Hello | undefined;
  welcome?: Welcome | undefined;
  envelope?: Envelope | undefined;
  subscribe?: Subscribe | undefined;
  unsubscribe?: Unsubscribe | undefined;
  backfilled?: Backfilled | undefined;
  gap?: Gap | undefined;
  presence?: Presence | undefined;
  ping?: Ping | undefined;
  pong?: Pong | undefined;
  error?:
    | Error
    | undefined;
  /** defined in identity.proto */
  challenge?: Challenge | undefined;
}

/** principal -> hub, the first frame a principal sends, answering the hub's Challenge. */
export interface Hello {
  /** the newest protocol major this peer speaks; the hub answers with the one it chose, or Error{UNSUPPORTED} */
  protocol: number;
  /** SHA-256 of the leaf certificate's subject key. (Development mode: any bytes, trusted as claimed.) */
  principal: Uint8Array;
  role: Role;
  /** Development mode only: the account, as given. Ignored when the hub authenticates. */
  accountCredential: Uint8Array;
  /** the account root's Ed25519 public key; SHA-256 of it is the account id */
  accountRoot: Uint8Array;
  /** leaf first, each issued by the next, the last issued by `account_root`; one or two certificates */
  chain: Certificate[];
  /**
   * Ed25519 by the leaf key over the hello transcript: "wmlhub/hello/v1" || 0x00 || u32be(len hub) || hub ||
   * nonce || u32be(len principal) || principal || u32be(role) || account id (crates/keys: hello_transcript)
   */
  signature: Uint8Array;
  /** a hub-operator invite, needed only to register an account the hub does not know, when registration is invite-only */
  invite: Uint8Array;
}

/** hub -> principal, answering Hello. */
export interface Welcome {
  protocol: number;
  /** the hub's clock, epoch ms, when it sent this; with the round trip, a peer estimates the hub's clock offset */
  serverTimeMs: number;
  limits: Limits | undefined;
}

/** What the hub will accept from this connection. A peer that exceeds one is disconnected, not throttled silently. */
export interface Limits {
  maxFrameBytes: number;
  maxPayloadBytes: number;
  /** envelopes retained per stream, by kind; 0 means the kind is not retained */
  ringSessionEvents: number;
  ringTelemetry: number;
  /**
   * Work the account may cause, shared by all its connections: every message at its size plus 64 bytes a frame, and
   * 64 bytes for each frame the hub queues on its behalf. Past the rate the hub stops reading until the debt is repaid,
   * so a client that sends faster simply goes slower. A client pacing itself below this is never delayed.
   */
  accountBytesPerSecond: number;
  accountBurstBytes: number;
}

/**
 * A publisher's stream: a channel of one principal. `channel` is opaque bytes the publisher chose; it is routing
 * metadata the hub sees, so a publisher should not put a session hash in it verbatim (docs/PROTOCOL.md).
 */
export interface StreamRef {
  publisher: Uint8Array;
  channel: Uint8Array;
}

/** Either way. The only frame that carries user data, and that data is `payload`. */
export interface Envelope {
  principal?:
    | Uint8Array
    | undefined;
  /** published on this channel of the SENDER; the publisher part is the sender, never a field a peer sets */
  channel?: Uint8Array | undefined;
  kind: Kind;
  /**
   * Set by the hub on delivery from the connection it arrived on. Ignored when a peer sends it: nothing can
   * claim to be another principal to the hub. (The payload's own signature is what a runtime trusts.)
   */
  sender: Uint8Array;
  /** Set by the hub on delivery of a published envelope: strictly increasing within one stream's `epoch`. */
  seq: number;
  /**
   * Set by the hub on delivery of a published envelope: identifies the ring the seq belongs to. A ring recreated
   * (a hub restart) has a new epoch, and a seq from another epoch means nothing.
   */
  epoch: number;
  /**
   * Telemetry only: a queued envelope on the same stream with the same non-empty `coalesce` is replaced by this
   * one. Opaque to the hub.
   */
  coalesce: Uint8Array;
  /** Chosen by the sender and echoed on an Error about this envelope. Not unique beyond the sender's own use. */
  ref: number;
  /** End-to-end ciphertext. Never decoded, logged or inspected by the hub. */
  payload: Uint8Array;
}

/** client -> hub: deliver a stream, starting after `since` when the client holds part of it. */
export interface Subscribe {
  stream:
    | StreamRef
    | undefined;
  /** absent: from the oldest retained envelope */
  since: Position | undefined;
}

export interface Position {
  epoch: number;
  seq: number;
}

export interface Unsubscribe {
  stream: StreamRef | undefined;
}

/** hub -> client: the backfill for a Subscribe is complete; live envelopes follow. */
export interface Backfilled {
  stream: StreamRef | undefined;
  epoch: number;
  /** the newest seq delivered so far; 0 when nothing was */
  seq: number;
  /**
   * true when `since` was older than the ring holds, or from another epoch: the client's record has a gap before
   * the first envelope it was sent
   */
  truncated: boolean;
}

/** hub -> client: telemetry on a stream was dropped for this subscriber because it fell behind. */
export interface Gap {
  stream: StreamRef | undefined;
  epoch: number;
  /** envelopes dropped since the previous Gap on this stream */
  dropped: number;
  /** the first seq delivered after the gap */
  resumeSeq: number;
}

/**
 * hub -> principal: a principal of the same account connected or disconnected. Sent for every online principal
 * right after Welcome, then on each change. This is the account's directory; nothing outside the account appears.
 */
export interface Presence {
  principal: Uint8Array;
  role: Role;
  online: boolean;
}

export interface Ping {
  nonce: number;
}

export interface Pong {
  nonce: number;
}

export interface Error {
  code: Error_Code;
  /** the `ref` of the envelope this is about, when it is about one */
  ref: number;
  /** for a person reading a log; never parsed */
  message: string;
}

export enum Error_Code {
  CODE_UNSPECIFIED = 0,
  /** CODE_UNSUPPORTED - a frame body, protocol version or kind this hub does not handle */
  CODE_UNSUPPORTED = 1,
  /** CODE_UNAUTHENTICATED - Hello rejected: bad credential or a principal already connected elsewhere */
  CODE_UNAUTHENTICATED = 2,
  /** CODE_INVALID - malformed frame or envelope (both or neither of principal/channel, a wrong kind for the direction) */
  CODE_INVALID = 3,
  /** CODE_UNAVAILABLE - direct envelope to a principal that is not online in this account */
  CODE_UNAVAILABLE = 4,
  /** CODE_LIMIT - a limit in Welcome was exceeded; the connection closes after this */
  CODE_LIMIT = 5,
  /** CODE_SLOW_CONSUMER - a subscriber fell behind on KIND_SESSION_EVENTS; the connection closes after this, and it resubscribes */
  CODE_SLOW_CONSUMER = 6,
  /**
   * CODE_THROTTLED - The account is over its work rate (Welcome.limits.account_bytes_per_second): the hub is reading this connection
   * more slowly until the debt is repaid. Nothing was dropped and the connection stays open. Sent for a wait of 100 ms or
   * more, at most once per connection every 10 seconds.
   */
  CODE_THROTTLED = 7,
  UNRECOGNIZED = -1,
}

function createBaseFrame(): Frame {
  return {
    hello: undefined,
    welcome: undefined,
    envelope: undefined,
    subscribe: undefined,
    unsubscribe: undefined,
    backfilled: undefined,
    gap: undefined,
    presence: undefined,
    ping: undefined,
    pong: undefined,
    error: undefined,
    challenge: undefined,
  };
}

export const Frame: MessageFns<Frame> = {
  encode(message: Frame, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.hello !== undefined) {
      Hello.encode(message.hello, writer.uint32(10).fork()).join();
    }
    if (message.welcome !== undefined) {
      Welcome.encode(message.welcome, writer.uint32(18).fork()).join();
    }
    if (message.envelope !== undefined) {
      Envelope.encode(message.envelope, writer.uint32(26).fork()).join();
    }
    if (message.subscribe !== undefined) {
      Subscribe.encode(message.subscribe, writer.uint32(34).fork()).join();
    }
    if (message.unsubscribe !== undefined) {
      Unsubscribe.encode(message.unsubscribe, writer.uint32(42).fork()).join();
    }
    if (message.backfilled !== undefined) {
      Backfilled.encode(message.backfilled, writer.uint32(50).fork()).join();
    }
    if (message.gap !== undefined) {
      Gap.encode(message.gap, writer.uint32(58).fork()).join();
    }
    if (message.presence !== undefined) {
      Presence.encode(message.presence, writer.uint32(66).fork()).join();
    }
    if (message.ping !== undefined) {
      Ping.encode(message.ping, writer.uint32(74).fork()).join();
    }
    if (message.pong !== undefined) {
      Pong.encode(message.pong, writer.uint32(82).fork()).join();
    }
    if (message.error !== undefined) {
      Error.encode(message.error, writer.uint32(90).fork()).join();
    }
    if (message.challenge !== undefined) {
      Challenge.encode(message.challenge, writer.uint32(98).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Frame {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseFrame();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.hello = Hello.decode(reader, reader.uint32());
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.welcome = Welcome.decode(reader, reader.uint32());
            continue;
          }
          case 3: {
            if (tag !== 26) {
              break;
            }

            message.envelope = Envelope.decode(reader, reader.uint32());
            continue;
          }
          case 4: {
            if (tag !== 34) {
              break;
            }

            message.subscribe = Subscribe.decode(reader, reader.uint32());
            continue;
          }
          case 5: {
            if (tag !== 42) {
              break;
            }

            message.unsubscribe = Unsubscribe.decode(reader, reader.uint32());
            continue;
          }
          case 6: {
            if (tag !== 50) {
              break;
            }

            message.backfilled = Backfilled.decode(reader, reader.uint32());
            continue;
          }
          case 7: {
            if (tag !== 58) {
              break;
            }

            message.gap = Gap.decode(reader, reader.uint32());
            continue;
          }
          case 8: {
            if (tag !== 66) {
              break;
            }

            message.presence = Presence.decode(reader, reader.uint32());
            continue;
          }
          case 9: {
            if (tag !== 74) {
              break;
            }

            message.ping = Ping.decode(reader, reader.uint32());
            continue;
          }
          case 10: {
            if (tag !== 82) {
              break;
            }

            message.pong = Pong.decode(reader, reader.uint32());
            continue;
          }
          case 11: {
            if (tag !== 90) {
              break;
            }

            message.error = Error.decode(reader, reader.uint32());
            continue;
          }
          case 12: {
            if (tag !== 98) {
              break;
            }

            message.challenge = Challenge.decode(reader, reader.uint32());
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create<I extends Exact<DeepPartial<Frame>, I>>(base?: I): Frame {
    return Frame.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Frame>, I>>(object: I): Frame {
    const message = createBaseFrame();
    message.hello = (object.hello !== undefined && object.hello !== null) ? Hello.fromPartial(object.hello) : undefined;
    message.welcome = (object.welcome !== undefined && object.welcome !== null)
      ? Welcome.fromPartial(object.welcome)
      : undefined;
    message.envelope = (object.envelope !== undefined && object.envelope !== null)
      ? Envelope.fromPartial(object.envelope)
      : undefined;
    message.subscribe = (object.subscribe !== undefined && object.subscribe !== null)
      ? Subscribe.fromPartial(object.subscribe)
      : undefined;
    message.unsubscribe = (object.unsubscribe !== undefined && object.unsubscribe !== null)
      ? Unsubscribe.fromPartial(object.unsubscribe)
      : undefined;
    message.backfilled = (object.backfilled !== undefined && object.backfilled !== null)
      ? Backfilled.fromPartial(object.backfilled)
      : undefined;
    message.gap = (object.gap !== undefined && object.gap !== null) ? Gap.fromPartial(object.gap) : undefined;
    message.presence = (object.presence !== undefined && object.presence !== null)
      ? Presence.fromPartial(object.presence)
      : undefined;
    message.ping = (object.ping !== undefined && object.ping !== null) ? Ping.fromPartial(object.ping) : undefined;
    message.pong = (object.pong !== undefined && object.pong !== null) ? Pong.fromPartial(object.pong) : undefined;
    message.error = (object.error !== undefined && object.error !== null) ? Error.fromPartial(object.error) : undefined;
    message.challenge = (object.challenge !== undefined && object.challenge !== null)
      ? Challenge.fromPartial(object.challenge)
      : undefined;
    return message;
  },
};

function createBaseHello(): Hello {
  return {
    protocol: 0,
    principal: new Uint8Array(0),
    role: 0,
    accountCredential: new Uint8Array(0),
    accountRoot: new Uint8Array(0),
    chain: [],
    signature: new Uint8Array(0),
    invite: new Uint8Array(0),
  };
}

export const Hello: MessageFns<Hello> = {
  encode(message: Hello, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.protocol !== 0) {
      writer.uint32(8).uint32(message.protocol);
    }
    if (message.principal.length !== 0) {
      writer.uint32(18).bytes(message.principal);
    }
    if (message.role !== 0) {
      writer.uint32(24).int32(message.role);
    }
    if (message.accountCredential.length !== 0) {
      writer.uint32(34).bytes(message.accountCredential);
    }
    if (message.accountRoot.length !== 0) {
      writer.uint32(42).bytes(message.accountRoot);
    }
    for (const v of message.chain) {
      Certificate.encode(v!, writer.uint32(50).fork()).join();
    }
    if (message.signature.length !== 0) {
      writer.uint32(58).bytes(message.signature);
    }
    if (message.invite.length !== 0) {
      writer.uint32(66).bytes(message.invite);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Hello {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseHello();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 8) {
              break;
            }

            message.protocol = reader.uint32();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.principal = reader.bytes();
            continue;
          }
          case 3: {
            if (tag !== 24) {
              break;
            }

            message.role = reader.int32() as any;
            continue;
          }
          case 4: {
            if (tag !== 34) {
              break;
            }

            message.accountCredential = reader.bytes();
            continue;
          }
          case 5: {
            if (tag !== 42) {
              break;
            }

            message.accountRoot = reader.bytes();
            continue;
          }
          case 6: {
            if (tag !== 50) {
              break;
            }

            message.chain.push(Certificate.decode(reader, reader.uint32()));
            continue;
          }
          case 7: {
            if (tag !== 58) {
              break;
            }

            message.signature = reader.bytes();
            continue;
          }
          case 8: {
            if (tag !== 66) {
              break;
            }

            message.invite = reader.bytes();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create<I extends Exact<DeepPartial<Hello>, I>>(base?: I): Hello {
    return Hello.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Hello>, I>>(object: I): Hello {
    const message = createBaseHello();
    message.protocol = object.protocol ?? 0;
    message.principal = object.principal ?? new Uint8Array(0);
    message.role = object.role ?? 0;
    message.accountCredential = object.accountCredential ?? new Uint8Array(0);
    message.accountRoot = object.accountRoot ?? new Uint8Array(0);
    message.chain = object.chain?.map((e) => Certificate.fromPartial(e)) || [];
    message.signature = object.signature ?? new Uint8Array(0);
    message.invite = object.invite ?? new Uint8Array(0);
    return message;
  },
};

function createBaseWelcome(): Welcome {
  return { protocol: 0, serverTimeMs: 0, limits: undefined };
}

export const Welcome: MessageFns<Welcome> = {
  encode(message: Welcome, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.protocol !== 0) {
      writer.uint32(8).uint32(message.protocol);
    }
    if (message.serverTimeMs !== 0) {
      writer.uint32(16).uint64(message.serverTimeMs);
    }
    if (message.limits !== undefined) {
      Limits.encode(message.limits, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Welcome {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseWelcome();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 8) {
              break;
            }

            message.protocol = reader.uint32();
            continue;
          }
          case 2: {
            if (tag !== 16) {
              break;
            }

            message.serverTimeMs = longToNumber(reader.uint64());
            continue;
          }
          case 3: {
            if (tag !== 26) {
              break;
            }

            message.limits = Limits.decode(reader, reader.uint32());
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create<I extends Exact<DeepPartial<Welcome>, I>>(base?: I): Welcome {
    return Welcome.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Welcome>, I>>(object: I): Welcome {
    const message = createBaseWelcome();
    message.protocol = object.protocol ?? 0;
    message.serverTimeMs = object.serverTimeMs ?? 0;
    message.limits = (object.limits !== undefined && object.limits !== null)
      ? Limits.fromPartial(object.limits)
      : undefined;
    return message;
  },
};

function createBaseLimits(): Limits {
  return {
    maxFrameBytes: 0,
    maxPayloadBytes: 0,
    ringSessionEvents: 0,
    ringTelemetry: 0,
    accountBytesPerSecond: 0,
    accountBurstBytes: 0,
  };
}

export const Limits: MessageFns<Limits> = {
  encode(message: Limits, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.maxFrameBytes !== 0) {
      writer.uint32(8).uint32(message.maxFrameBytes);
    }
    if (message.maxPayloadBytes !== 0) {
      writer.uint32(16).uint32(message.maxPayloadBytes);
    }
    if (message.ringSessionEvents !== 0) {
      writer.uint32(24).uint32(message.ringSessionEvents);
    }
    if (message.ringTelemetry !== 0) {
      writer.uint32(32).uint32(message.ringTelemetry);
    }
    if (message.accountBytesPerSecond !== 0) {
      writer.uint32(40).uint64(message.accountBytesPerSecond);
    }
    if (message.accountBurstBytes !== 0) {
      writer.uint32(48).uint64(message.accountBurstBytes);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Limits {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseLimits();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 8) {
              break;
            }

            message.maxFrameBytes = reader.uint32();
            continue;
          }
          case 2: {
            if (tag !== 16) {
              break;
            }

            message.maxPayloadBytes = reader.uint32();
            continue;
          }
          case 3: {
            if (tag !== 24) {
              break;
            }

            message.ringSessionEvents = reader.uint32();
            continue;
          }
          case 4: {
            if (tag !== 32) {
              break;
            }

            message.ringTelemetry = reader.uint32();
            continue;
          }
          case 5: {
            if (tag !== 40) {
              break;
            }

            message.accountBytesPerSecond = longToNumber(reader.uint64());
            continue;
          }
          case 6: {
            if (tag !== 48) {
              break;
            }

            message.accountBurstBytes = longToNumber(reader.uint64());
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create<I extends Exact<DeepPartial<Limits>, I>>(base?: I): Limits {
    return Limits.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Limits>, I>>(object: I): Limits {
    const message = createBaseLimits();
    message.maxFrameBytes = object.maxFrameBytes ?? 0;
    message.maxPayloadBytes = object.maxPayloadBytes ?? 0;
    message.ringSessionEvents = object.ringSessionEvents ?? 0;
    message.ringTelemetry = object.ringTelemetry ?? 0;
    message.accountBytesPerSecond = object.accountBytesPerSecond ?? 0;
    message.accountBurstBytes = object.accountBurstBytes ?? 0;
    return message;
  },
};

function createBaseStreamRef(): StreamRef {
  return { publisher: new Uint8Array(0), channel: new Uint8Array(0) };
}

export const StreamRef: MessageFns<StreamRef> = {
  encode(message: StreamRef, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.publisher.length !== 0) {
      writer.uint32(10).bytes(message.publisher);
    }
    if (message.channel.length !== 0) {
      writer.uint32(18).bytes(message.channel);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StreamRef {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseStreamRef();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.publisher = reader.bytes();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.channel = reader.bytes();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create<I extends Exact<DeepPartial<StreamRef>, I>>(base?: I): StreamRef {
    return StreamRef.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StreamRef>, I>>(object: I): StreamRef {
    const message = createBaseStreamRef();
    message.publisher = object.publisher ?? new Uint8Array(0);
    message.channel = object.channel ?? new Uint8Array(0);
    return message;
  },
};

function createBaseEnvelope(): Envelope {
  return {
    principal: undefined,
    channel: undefined,
    kind: 0,
    sender: new Uint8Array(0),
    seq: 0,
    epoch: 0,
    coalesce: new Uint8Array(0),
    ref: 0,
    payload: new Uint8Array(0),
  };
}

export const Envelope: MessageFns<Envelope> = {
  encode(message: Envelope, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.principal !== undefined) {
      writer.uint32(10).bytes(message.principal);
    }
    if (message.channel !== undefined) {
      writer.uint32(18).bytes(message.channel);
    }
    if (message.kind !== 0) {
      writer.uint32(24).int32(message.kind);
    }
    if (message.sender.length !== 0) {
      writer.uint32(34).bytes(message.sender);
    }
    if (message.seq !== 0) {
      writer.uint32(40).uint64(message.seq);
    }
    if (message.epoch !== 0) {
      writer.uint32(48).uint64(message.epoch);
    }
    if (message.coalesce.length !== 0) {
      writer.uint32(58).bytes(message.coalesce);
    }
    if (message.ref !== 0) {
      writer.uint32(64).uint64(message.ref);
    }
    if (message.payload.length !== 0) {
      writer.uint32(122).bytes(message.payload);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Envelope {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseEnvelope();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.principal = reader.bytes();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.channel = reader.bytes();
            continue;
          }
          case 3: {
            if (tag !== 24) {
              break;
            }

            message.kind = reader.int32() as any;
            continue;
          }
          case 4: {
            if (tag !== 34) {
              break;
            }

            message.sender = reader.bytes();
            continue;
          }
          case 5: {
            if (tag !== 40) {
              break;
            }

            message.seq = longToNumber(reader.uint64());
            continue;
          }
          case 6: {
            if (tag !== 48) {
              break;
            }

            message.epoch = longToNumber(reader.uint64());
            continue;
          }
          case 7: {
            if (tag !== 58) {
              break;
            }

            message.coalesce = reader.bytes();
            continue;
          }
          case 8: {
            if (tag !== 64) {
              break;
            }

            message.ref = longToNumber(reader.uint64());
            continue;
          }
          case 15: {
            if (tag !== 122) {
              break;
            }

            message.payload = reader.bytes();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create<I extends Exact<DeepPartial<Envelope>, I>>(base?: I): Envelope {
    return Envelope.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Envelope>, I>>(object: I): Envelope {
    const message = createBaseEnvelope();
    message.principal = object.principal ?? undefined;
    message.channel = object.channel ?? undefined;
    message.kind = object.kind ?? 0;
    message.sender = object.sender ?? new Uint8Array(0);
    message.seq = object.seq ?? 0;
    message.epoch = object.epoch ?? 0;
    message.coalesce = object.coalesce ?? new Uint8Array(0);
    message.ref = object.ref ?? 0;
    message.payload = object.payload ?? new Uint8Array(0);
    return message;
  },
};

function createBaseSubscribe(): Subscribe {
  return { stream: undefined, since: undefined };
}

export const Subscribe: MessageFns<Subscribe> = {
  encode(message: Subscribe, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.stream !== undefined) {
      StreamRef.encode(message.stream, writer.uint32(10).fork()).join();
    }
    if (message.since !== undefined) {
      Position.encode(message.since, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Subscribe {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseSubscribe();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.stream = StreamRef.decode(reader, reader.uint32());
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.since = Position.decode(reader, reader.uint32());
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create<I extends Exact<DeepPartial<Subscribe>, I>>(base?: I): Subscribe {
    return Subscribe.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Subscribe>, I>>(object: I): Subscribe {
    const message = createBaseSubscribe();
    message.stream = (object.stream !== undefined && object.stream !== null)
      ? StreamRef.fromPartial(object.stream)
      : undefined;
    message.since = (object.since !== undefined && object.since !== null)
      ? Position.fromPartial(object.since)
      : undefined;
    return message;
  },
};

function createBasePosition(): Position {
  return { epoch: 0, seq: 0 };
}

export const Position: MessageFns<Position> = {
  encode(message: Position, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.epoch !== 0) {
      writer.uint32(8).uint64(message.epoch);
    }
    if (message.seq !== 0) {
      writer.uint32(16).uint64(message.seq);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Position {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBasePosition();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 8) {
              break;
            }

            message.epoch = longToNumber(reader.uint64());
            continue;
          }
          case 2: {
            if (tag !== 16) {
              break;
            }

            message.seq = longToNumber(reader.uint64());
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create<I extends Exact<DeepPartial<Position>, I>>(base?: I): Position {
    return Position.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Position>, I>>(object: I): Position {
    const message = createBasePosition();
    message.epoch = object.epoch ?? 0;
    message.seq = object.seq ?? 0;
    return message;
  },
};

function createBaseUnsubscribe(): Unsubscribe {
  return { stream: undefined };
}

export const Unsubscribe: MessageFns<Unsubscribe> = {
  encode(message: Unsubscribe, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.stream !== undefined) {
      StreamRef.encode(message.stream, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Unsubscribe {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseUnsubscribe();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.stream = StreamRef.decode(reader, reader.uint32());
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create<I extends Exact<DeepPartial<Unsubscribe>, I>>(base?: I): Unsubscribe {
    return Unsubscribe.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Unsubscribe>, I>>(object: I): Unsubscribe {
    const message = createBaseUnsubscribe();
    message.stream = (object.stream !== undefined && object.stream !== null)
      ? StreamRef.fromPartial(object.stream)
      : undefined;
    return message;
  },
};

function createBaseBackfilled(): Backfilled {
  return { stream: undefined, epoch: 0, seq: 0, truncated: false };
}

export const Backfilled: MessageFns<Backfilled> = {
  encode(message: Backfilled, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.stream !== undefined) {
      StreamRef.encode(message.stream, writer.uint32(10).fork()).join();
    }
    if (message.epoch !== 0) {
      writer.uint32(16).uint64(message.epoch);
    }
    if (message.seq !== 0) {
      writer.uint32(24).uint64(message.seq);
    }
    if (message.truncated !== false) {
      writer.uint32(32).bool(message.truncated);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Backfilled {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseBackfilled();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.stream = StreamRef.decode(reader, reader.uint32());
            continue;
          }
          case 2: {
            if (tag !== 16) {
              break;
            }

            message.epoch = longToNumber(reader.uint64());
            continue;
          }
          case 3: {
            if (tag !== 24) {
              break;
            }

            message.seq = longToNumber(reader.uint64());
            continue;
          }
          case 4: {
            if (tag !== 32) {
              break;
            }

            message.truncated = reader.bool();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create<I extends Exact<DeepPartial<Backfilled>, I>>(base?: I): Backfilled {
    return Backfilled.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Backfilled>, I>>(object: I): Backfilled {
    const message = createBaseBackfilled();
    message.stream = (object.stream !== undefined && object.stream !== null)
      ? StreamRef.fromPartial(object.stream)
      : undefined;
    message.epoch = object.epoch ?? 0;
    message.seq = object.seq ?? 0;
    message.truncated = object.truncated ?? false;
    return message;
  },
};

function createBaseGap(): Gap {
  return { stream: undefined, epoch: 0, dropped: 0, resumeSeq: 0 };
}

export const Gap: MessageFns<Gap> = {
  encode(message: Gap, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.stream !== undefined) {
      StreamRef.encode(message.stream, writer.uint32(10).fork()).join();
    }
    if (message.epoch !== 0) {
      writer.uint32(16).uint64(message.epoch);
    }
    if (message.dropped !== 0) {
      writer.uint32(24).uint64(message.dropped);
    }
    if (message.resumeSeq !== 0) {
      writer.uint32(32).uint64(message.resumeSeq);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Gap {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseGap();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.stream = StreamRef.decode(reader, reader.uint32());
            continue;
          }
          case 2: {
            if (tag !== 16) {
              break;
            }

            message.epoch = longToNumber(reader.uint64());
            continue;
          }
          case 3: {
            if (tag !== 24) {
              break;
            }

            message.dropped = longToNumber(reader.uint64());
            continue;
          }
          case 4: {
            if (tag !== 32) {
              break;
            }

            message.resumeSeq = longToNumber(reader.uint64());
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create<I extends Exact<DeepPartial<Gap>, I>>(base?: I): Gap {
    return Gap.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Gap>, I>>(object: I): Gap {
    const message = createBaseGap();
    message.stream = (object.stream !== undefined && object.stream !== null)
      ? StreamRef.fromPartial(object.stream)
      : undefined;
    message.epoch = object.epoch ?? 0;
    message.dropped = object.dropped ?? 0;
    message.resumeSeq = object.resumeSeq ?? 0;
    return message;
  },
};

function createBasePresence(): Presence {
  return { principal: new Uint8Array(0), role: 0, online: false };
}

export const Presence: MessageFns<Presence> = {
  encode(message: Presence, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.principal.length !== 0) {
      writer.uint32(10).bytes(message.principal);
    }
    if (message.role !== 0) {
      writer.uint32(16).int32(message.role);
    }
    if (message.online !== false) {
      writer.uint32(24).bool(message.online);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Presence {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBasePresence();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.principal = reader.bytes();
            continue;
          }
          case 2: {
            if (tag !== 16) {
              break;
            }

            message.role = reader.int32() as any;
            continue;
          }
          case 3: {
            if (tag !== 24) {
              break;
            }

            message.online = reader.bool();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create<I extends Exact<DeepPartial<Presence>, I>>(base?: I): Presence {
    return Presence.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Presence>, I>>(object: I): Presence {
    const message = createBasePresence();
    message.principal = object.principal ?? new Uint8Array(0);
    message.role = object.role ?? 0;
    message.online = object.online ?? false;
    return message;
  },
};

function createBasePing(): Ping {
  return { nonce: 0 };
}

export const Ping: MessageFns<Ping> = {
  encode(message: Ping, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.nonce !== 0) {
      writer.uint32(8).uint64(message.nonce);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Ping {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBasePing();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 8) {
              break;
            }

            message.nonce = longToNumber(reader.uint64());
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create<I extends Exact<DeepPartial<Ping>, I>>(base?: I): Ping {
    return Ping.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Ping>, I>>(object: I): Ping {
    const message = createBasePing();
    message.nonce = object.nonce ?? 0;
    return message;
  },
};

function createBasePong(): Pong {
  return { nonce: 0 };
}

export const Pong: MessageFns<Pong> = {
  encode(message: Pong, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.nonce !== 0) {
      writer.uint32(8).uint64(message.nonce);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Pong {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBasePong();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 8) {
              break;
            }

            message.nonce = longToNumber(reader.uint64());
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create<I extends Exact<DeepPartial<Pong>, I>>(base?: I): Pong {
    return Pong.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Pong>, I>>(object: I): Pong {
    const message = createBasePong();
    message.nonce = object.nonce ?? 0;
    return message;
  },
};

function createBaseError(): Error {
  return { code: 0, ref: 0, message: "" };
}

export const Error: MessageFns<Error> = {
  encode(message: Error, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.code !== 0) {
      writer.uint32(8).int32(message.code);
    }
    if (message.ref !== 0) {
      writer.uint32(16).uint64(message.ref);
    }
    if (message.message !== "") {
      writer.uint32(26).string(message.message);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Error {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseError();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 8) {
              break;
            }

            message.code = reader.int32() as any;
            continue;
          }
          case 2: {
            if (tag !== 16) {
              break;
            }

            message.ref = longToNumber(reader.uint64());
            continue;
          }
          case 3: {
            if (tag !== 26) {
              break;
            }

            message.message = reader.string();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create<I extends Exact<DeepPartial<Error>, I>>(base?: I): Error {
    return Error.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Error>, I>>(object: I): Error {
    const message = createBaseError();
    message.code = object.code ?? 0;
    message.ref = object.ref ?? 0;
    message.message = object.message ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
