// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.1
//   protoc               v7.35.1
// source: wmlhub/v1/identity.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "wmlhub.v1";

/**
 * What a connection is, in the hub's routing. It changes nothing a runtime trusts: a runtime decides what to do
 * with a command from its own allowlist of keys, never from a role the hub reports.
 */
export enum Role {
  ROLE_UNSPECIFIED = 0,
  /** ROLE_RUNTIME - runs sessions and publishes their events (the extension, a desktop daemon) */
  ROLE_RUNTIME = 1,
  /** ROLE_CLIENT - shows sessions and sends commands (a phone, the chat page, an agent client) */
  ROLE_CLIENT = 2,
  /** ROLE_BOX_CONNECTOR - relays one box's telemetry */
  ROLE_BOX_CONNECTOR = 3,
  UNRECOGNIZED = -1,
}

/**
 * The signed bytes and the signature over them. `body` is an encoded CertificateBody and is verified exactly as
 * transmitted, never re-encoded, so no canonical encoding is needed.
 */
export interface Certificate {
  body: Uint8Array;
  /** Ed25519, by `CertificateBody.issuer`, over "wmlhub/cert/v1" || 0x00 || body */
  signature: Uint8Array;
}

export interface CertificateBody {
  /** the holder's Ed25519 identity public key (32 bytes); its SHA-256 is the principal id */
  subject: Uint8Array;
  /** the holder's X25519 public key (32 bytes), bound to the identity by this signature: what others seal to */
  agreementKey: Uint8Array;
  /** the signer's Ed25519 public key: the account root, or a principal whose own certificate has `may_pair` */
  issuer: Uint8Array;
  role: Role;
  /**
   * Granted scopes, by name: what the holder may ask a runtime to do (window-ml docs/spec/RUNTIME_HUB.md §Principals
   * and scopes: `view`, `drive`, `approve`, `screen`, `desktop`, and later names such as `control`). Strings, not an
   * enum, because the set is open (window-ml docs/spec/SESSION_CONTRACT.md §Versioning): a name a runtime does not know
   * grants nothing there, and issuing one needs no schema change on any peer. The hub does not enforce scopes; it
   * checks only their shape (at most 16, each 1 to 32 bytes of `a-z 0-9 . _ -`) and that a certificate issued by a
   * non-root issuer carries only names the issuer's certificate carries.
   */
  scopes: string[];
  /** May issue certificates in turn (a second device that can pair new ones). Chains are at most two long. */
  mayPair: boolean;
  /** validity, epoch milliseconds; `not_after_ms` 0 means no expiry, and a child never outlives its issuer */
  notBeforeMs: number;
  notAfterMs: number;
  /** a name its owner chose ("phone"); display text, never proof of anything */
  label: string;
}

/** hub -> principal, the first frame on every connection: what the principal signs to prove it holds its key. */
export interface Challenge {
  /** 32 random bytes, fresh per connection */
  nonce: Uint8Array;
  /**
   * The hub's configured name. A client checks it is the hub it meant to reach before signing, so a malicious hub
   * cannot pass along another hub's challenge and log in there as the client.
   */
  hub: string;
  serverTimeMs: number;
}

function createBaseCertificate(): Certificate {
  return { body: new Uint8Array(0), signature: new Uint8Array(0) };
}

export const Certificate: MessageFns<Certificate> = {
  encode(message: Certificate, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.body.length !== 0) {
      writer.uint32(10).bytes(message.body);
    }
    if (message.signature.length !== 0) {
      writer.uint32(18).bytes(message.signature);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Certificate {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseCertificate();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.body = reader.bytes();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.signature = reader.bytes();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create<I extends Exact<DeepPartial<Certificate>, I>>(base?: I): Certificate {
    return Certificate.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Certificate>, I>>(object: I): Certificate {
    const message = createBaseCertificate();
    message.body = object.body ?? new Uint8Array(0);
    message.signature = object.signature ?? new Uint8Array(0);
    return message;
  },
};

function createBaseCertificateBody(): CertificateBody {
  return {
    subject: new Uint8Array(0),
    agreementKey: new Uint8Array(0),
    issuer: new Uint8Array(0),
    role: 0,
    scopes: [],
    mayPair: false,
    notBeforeMs: 0,
    notAfterMs: 0,
    label: "",
  };
}

export const CertificateBody: MessageFns<CertificateBody> = {
  encode(message: CertificateBody, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.subject.length !== 0) {
      writer.uint32(10).bytes(message.subject);
    }
    if (message.agreementKey.length !== 0) {
      writer.uint32(18).bytes(message.agreementKey);
    }
    if (message.issuer.length !== 0) {
      writer.uint32(26).bytes(message.issuer);
    }
    if (message.role !== 0) {
      writer.uint32(32).int32(message.role);
    }
    for (const v of message.scopes) {
      writer.uint32(82).string(v!);
    }
    if (message.mayPair !== false) {
      writer.uint32(48).bool(message.mayPair);
    }
    if (message.notBeforeMs !== 0) {
      writer.uint32(56).uint64(message.notBeforeMs);
    }
    if (message.notAfterMs !== 0) {
      writer.uint32(64).uint64(message.notAfterMs);
    }
    if (message.label !== "") {
      writer.uint32(74).string(message.label);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CertificateBody {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseCertificateBody();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.subject = reader.bytes();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.agreementKey = reader.bytes();
            continue;
          }
          case 3: {
            if (tag !== 26) {
              break;
            }

            message.issuer = reader.bytes();
            continue;
          }
          case 4: {
            if (tag !== 32) {
              break;
            }

            message.role = reader.int32() as any;
            continue;
          }
          case 10: {
            if (tag !== 82) {
              break;
            }

            message.scopes.push(reader.string());
            continue;
          }
          case 6: {
            if (tag !== 48) {
              break;
            }

            message.mayPair = reader.bool();
            continue;
          }
          case 7: {
            if (tag !== 56) {
              break;
            }

            message.notBeforeMs = longToNumber(reader.uint64());
            continue;
          }
          case 8: {
            if (tag !== 64) {
              break;
            }

            message.notAfterMs = longToNumber(reader.uint64());
            continue;
          }
          case 9: {
            if (tag !== 74) {
              break;
            }

            message.label = reader.string();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create<I extends Exact<DeepPartial<CertificateBody>, I>>(base?: I): CertificateBody {
    return CertificateBody.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CertificateBody>, I>>(object: I): CertificateBody {
    const message = createBaseCertificateBody();
    message.subject = object.subject ?? new Uint8Array(0);
    message.agreementKey = object.agreementKey ?? new Uint8Array(0);
    message.issuer = object.issuer ?? new Uint8Array(0);
    message.role = object.role ?? 0;
    message.scopes = object.scopes?.map((e) => e) || [];
    message.mayPair = object.mayPair ?? false;
    message.notBeforeMs = object.notBeforeMs ?? 0;
    message.notAfterMs = object.notAfterMs ?? 0;
    message.label = object.label ?? "";
    return message;
  },
};

function createBaseChallenge(): Challenge {
  return { nonce: new Uint8Array(0), hub: "", serverTimeMs: 0 };
}

export const Challenge: MessageFns<Challenge> = {
  encode(message: Challenge, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.nonce.length !== 0) {
      writer.uint32(10).bytes(message.nonce);
    }
    if (message.hub !== "") {
      writer.uint32(18).string(message.hub);
    }
    if (message.serverTimeMs !== 0) {
      writer.uint32(24).uint64(message.serverTimeMs);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Challenge {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseChallenge();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.nonce = reader.bytes();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.hub = reader.string();
            continue;
          }
          case 3: {
            if (tag !== 24) {
              break;
            }

            message.serverTimeMs = longToNumber(reader.uint64());
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create<I extends Exact<DeepPartial<Challenge>, I>>(base?: I): Challenge {
    return Challenge.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Challenge>, I>>(object: I): Challenge {
    const message = createBaseChallenge();
    message.nonce = object.nonce ?? new Uint8Array(0);
    message.hub = object.hub ?? "";
    message.serverTimeMs = object.serverTimeMs ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
