// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.1
//   protoc               v7.35.1
// source: wmlhub/v1/seal.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Certificate } from "./identity.gen";

export const protobufPackage = "wmlhub.v1";

export interface Sealed {
  /** the HPKE encapsulated key: an ephemeral X25519 public key, 32 bytes */
  enc: Uint8Array;
  /** HPKE ciphertext of an encoded SignedCommand, AEAD tag included */
  ciphertext: Uint8Array;
}

export interface SignedCommand {
  /** an encoded CommandBody, verified exactly as transmitted, never re-encoded */
  body: Uint8Array;
  /** Ed25519 by the sender's leaf identity key over "wmlhub/command/v1" || 0x00 || body */
  signature: Uint8Array;
  /**
   * the sender's certificate chain, leaf first, so the recipient can check it reaches the account root and grants
   * `scope`
   */
  chain: Certificate[];
}

export interface CommandBody {
  /** sender and recipient principal ids (SHA-256 of their identity keys) */
  from: Uint8Array;
  to: Uint8Array;
  /**
   * The scope the command needs (window-ml `COMMAND_SCOPE`), checked against the sender's leaf certificate. Empty on a
   * result.
   */
  scope: string;
  /** 16 random bytes, never reused by a sender; the recipient refuses one it has seen within the clock window */
  nonce: Uint8Array;
  /** the sender's wall clock, epoch milliseconds; refused outside the recipient's window */
  timeMs: number;
  /** the command or its result, as the session contract encodes it; opaque here */
  body: Uint8Array;
  /** on a result: the nonce of the command it answers. Empty on a command. */
  answers: Uint8Array;
}

export interface StreamFrame {
  /** which stream key opens this: SHA-256("wmlhub/streamkey-id/v1" || 0x00 || key), first 8 bytes */
  keyId: Uint8Array;
  /**
   * the publisher's own count for this channel, from 1, across key rotations; what a client orders by, since the hub's
   * `seq` is only a routing aid
   */
  counter: number;
  /** 12 bytes, fresh per frame */
  nonce: Uint8Array;
  /** AES-256-GCM of the batch, with the header below as associated data */
  ciphertext: Uint8Array;
  /**
   * Ed25519 by the publisher over "wmlhub/stream/v1" || 0x00 || header || ciphertext, where header is
   * publisher (32) || channel length (2, big endian) || channel || key_id (8) || counter (8, big endian) || nonce (12).
   * The header is what binds a frame to its channel, publisher, key and place in the stream: moved, renumbered or
   * spliced, it stops verifying.
   */
  signature: Uint8Array;
}

/**
 * A stream key handed to one device, sealed as a command is but under its own labels, so neither can be opened as the
 * other. The publisher wraps it, so the chain here is the publisher's own: it is also how a subscriber learns the key
 * that signs the stream's frames.
 */
export interface SignedGrant {
  body: Uint8Array;
  /** Ed25519 by the publisher over "wmlhub/grant/v1" || 0x00 || body */
  signature: Uint8Array;
  chain: Certificate[];
}

export interface GrantBody {
  from: Uint8Array;
  to: Uint8Array;
  nonce: Uint8Array;
  timeMs: number;
  /** the stream this key is for */
  channel: Uint8Array;
  keyId: Uint8Array;
  /** 32 bytes of AES-256-GCM key */
  key: Uint8Array;
  /** the first counter this key covers; frames before it need the previous key */
  fromCounter: number;
}

function createBaseSealed(): Sealed {
  return { enc: new Uint8Array(0), ciphertext: new Uint8Array(0) };
}

export const Sealed: MessageFns<Sealed> = {
  encode(message: Sealed, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.enc.length !== 0) {
      writer.uint32(10).bytes(message.enc);
    }
    if (message.ciphertext.length !== 0) {
      writer.uint32(18).bytes(message.ciphertext);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Sealed {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseSealed();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.enc = reader.bytes();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.ciphertext = reader.bytes();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create<I extends Exact<DeepPartial<Sealed>, I>>(base?: I): Sealed {
    return Sealed.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Sealed>, I>>(object: I): Sealed {
    const message = createBaseSealed();
    message.enc = object.enc ?? new Uint8Array(0);
    message.ciphertext = object.ciphertext ?? new Uint8Array(0);
    return message;
  },
};

function createBaseSignedCommand(): SignedCommand {
  return { body: new Uint8Array(0), signature: new Uint8Array(0), chain: [] };
}

export const SignedCommand: MessageFns<SignedCommand> = {
  encode(message: SignedCommand, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.body.length !== 0) {
      writer.uint32(10).bytes(message.body);
    }
    if (message.signature.length !== 0) {
      writer.uint32(18).bytes(message.signature);
    }
    for (const v of message.chain) {
      Certificate.encode(v!, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SignedCommand {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseSignedCommand();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.body = reader.bytes();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.signature = reader.bytes();
            continue;
          }
          case 3: {
            if (tag !== 26) {
              break;
            }

            message.chain.push(Certificate.decode(reader, reader.uint32()));
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create<I extends Exact<DeepPartial<SignedCommand>, I>>(base?: I): SignedCommand {
    return SignedCommand.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SignedCommand>, I>>(object: I): SignedCommand {
    const message = createBaseSignedCommand();
    message.body = object.body ?? new Uint8Array(0);
    message.signature = object.signature ?? new Uint8Array(0);
    message.chain = object.chain?.map((e) => Certificate.fromPartial(e)) || [];
    return message;
  },
};

function createBaseCommandBody(): CommandBody {
  return {
    from: new Uint8Array(0),
    to: new Uint8Array(0),
    scope: "",
    nonce: new Uint8Array(0),
    timeMs: 0,
    body: new Uint8Array(0),
    answers: new Uint8Array(0),
  };
}

export const CommandBody: MessageFns<CommandBody> = {
  encode(message: CommandBody, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.from.length !== 0) {
      writer.uint32(10).bytes(message.from);
    }
    if (message.to.length !== 0) {
      writer.uint32(18).bytes(message.to);
    }
    if (message.scope !== "") {
      writer.uint32(26).string(message.scope);
    }
    if (message.nonce.length !== 0) {
      writer.uint32(34).bytes(message.nonce);
    }
    if (message.timeMs !== 0) {
      writer.uint32(40).uint64(message.timeMs);
    }
    if (message.body.length !== 0) {
      writer.uint32(50).bytes(message.body);
    }
    if (message.answers.length !== 0) {
      writer.uint32(58).bytes(message.answers);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CommandBody {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseCommandBody();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.from = reader.bytes();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.to = reader.bytes();
            continue;
          }
          case 3: {
            if (tag !== 26) {
              break;
            }

            message.scope = reader.string();
            continue;
          }
          case 4: {
            if (tag !== 34) {
              break;
            }

            message.nonce = reader.bytes();
            continue;
          }
          case 5: {
            if (tag !== 40) {
              break;
            }

            message.timeMs = longToNumber(reader.uint64());
            continue;
          }
          case 6: {
            if (tag !== 50) {
              break;
            }

            message.body = reader.bytes();
            continue;
          }
          case 7: {
            if (tag !== 58) {
              break;
            }

            message.answers = reader.bytes();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create<I extends Exact<DeepPartial<CommandBody>, I>>(base?: I): CommandBody {
    return CommandBody.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CommandBody>, I>>(object: I): CommandBody {
    const message = createBaseCommandBody();
    message.from = object.from ?? new Uint8Array(0);
    message.to = object.to ?? new Uint8Array(0);
    message.scope = object.scope ?? "";
    message.nonce = object.nonce ?? new Uint8Array(0);
    message.timeMs = object.timeMs ?? 0;
    message.body = object.body ?? new Uint8Array(0);
    message.answers = object.answers ?? new Uint8Array(0);
    return message;
  },
};

function createBaseStreamFrame(): StreamFrame {
  return {
    keyId: new Uint8Array(0),
    counter: 0,
    nonce: new Uint8Array(0),
    ciphertext: new Uint8Array(0),
    signature: new Uint8Array(0),
  };
}

export const StreamFrame: MessageFns<StreamFrame> = {
  encode(message: StreamFrame, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.keyId.length !== 0) {
      writer.uint32(10).bytes(message.keyId);
    }
    if (message.counter !== 0) {
      writer.uint32(16).uint64(message.counter);
    }
    if (message.nonce.length !== 0) {
      writer.uint32(26).bytes(message.nonce);
    }
    if (message.ciphertext.length !== 0) {
      writer.uint32(34).bytes(message.ciphertext);
    }
    if (message.signature.length !== 0) {
      writer.uint32(42).bytes(message.signature);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StreamFrame {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseStreamFrame();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.keyId = reader.bytes();
            continue;
          }
          case 2: {
            if (tag !== 16) {
              break;
            }

            message.counter = longToNumber(reader.uint64());
            continue;
          }
          case 3: {
            if (tag !== 26) {
              break;
            }

            message.nonce = reader.bytes();
            continue;
          }
          case 4: {
            if (tag !== 34) {
              break;
            }

            message.ciphertext = reader.bytes();
            continue;
          }
          case 5: {
            if (tag !== 42) {
              break;
            }

            message.signature = reader.bytes();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create<I extends Exact<DeepPartial<StreamFrame>, I>>(base?: I): StreamFrame {
    return StreamFrame.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StreamFrame>, I>>(object: I): StreamFrame {
    const message = createBaseStreamFrame();
    message.keyId = object.keyId ?? new Uint8Array(0);
    message.counter = object.counter ?? 0;
    message.nonce = object.nonce ?? new Uint8Array(0);
    message.ciphertext = object.ciphertext ?? new Uint8Array(0);
    message.signature = object.signature ?? new Uint8Array(0);
    return message;
  },
};

function createBaseSignedGrant(): SignedGrant {
  return { body: new Uint8Array(0), signature: new Uint8Array(0), chain: [] };
}

export const SignedGrant: MessageFns<SignedGrant> = {
  encode(message: SignedGrant, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.body.length !== 0) {
      writer.uint32(10).bytes(message.body);
    }
    if (message.signature.length !== 0) {
      writer.uint32(18).bytes(message.signature);
    }
    for (const v of message.chain) {
      Certificate.encode(v!, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SignedGrant {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseSignedGrant();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.body = reader.bytes();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.signature = reader.bytes();
            continue;
          }
          case 3: {
            if (tag !== 26) {
              break;
            }

            message.chain.push(Certificate.decode(reader, reader.uint32()));
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create<I extends Exact<DeepPartial<SignedGrant>, I>>(base?: I): SignedGrant {
    return SignedGrant.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SignedGrant>, I>>(object: I): SignedGrant {
    const message = createBaseSignedGrant();
    message.body = object.body ?? new Uint8Array(0);
    message.signature = object.signature ?? new Uint8Array(0);
    message.chain = object.chain?.map((e) => Certificate.fromPartial(e)) || [];
    return message;
  },
};

function createBaseGrantBody(): GrantBody {
  return {
    from: new Uint8Array(0),
    to: new Uint8Array(0),
    nonce: new Uint8Array(0),
    timeMs: 0,
    channel: new Uint8Array(0),
    keyId: new Uint8Array(0),
    key: new Uint8Array(0),
    fromCounter: 0,
  };
}

export const GrantBody: MessageFns<GrantBody> = {
  encode(message: GrantBody, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.from.length !== 0) {
      writer.uint32(10).bytes(message.from);
    }
    if (message.to.length !== 0) {
      writer.uint32(18).bytes(message.to);
    }
    if (message.nonce.length !== 0) {
      writer.uint32(26).bytes(message.nonce);
    }
    if (message.timeMs !== 0) {
      writer.uint32(32).uint64(message.timeMs);
    }
    if (message.channel.length !== 0) {
      writer.uint32(42).bytes(message.channel);
    }
    if (message.keyId.length !== 0) {
      writer.uint32(50).bytes(message.keyId);
    }
    if (message.key.length !== 0) {
      writer.uint32(58).bytes(message.key);
    }
    if (message.fromCounter !== 0) {
      writer.uint32(64).uint64(message.fromCounter);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GrantBody {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseGrantBody();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.from = reader.bytes();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.to = reader.bytes();
            continue;
          }
          case 3: {
            if (tag !== 26) {
              break;
            }

            message.nonce = reader.bytes();
            continue;
          }
          case 4: {
            if (tag !== 32) {
              break;
            }

            message.timeMs = longToNumber(reader.uint64());
            continue;
          }
          case 5: {
            if (tag !== 42) {
              break;
            }

            message.channel = reader.bytes();
            continue;
          }
          case 6: {
            if (tag !== 50) {
              break;
            }

            message.keyId = reader.bytes();
            continue;
          }
          case 7: {
            if (tag !== 58) {
              break;
            }

            message.key = reader.bytes();
            continue;
          }
          case 8: {
            if (tag !== 64) {
              break;
            }

            message.fromCounter = longToNumber(reader.uint64());
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create<I extends Exact<DeepPartial<GrantBody>, I>>(base?: I): GrantBody {
    return GrantBody.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GrantBody>, I>>(object: I): GrantBody {
    const message = createBaseGrantBody();
    message.from = object.from ?? new Uint8Array(0);
    message.to = object.to ?? new Uint8Array(0);
    message.nonce = object.nonce ?? new Uint8Array(0);
    message.timeMs = object.timeMs ?? 0;
    message.channel = object.channel ?? new Uint8Array(0);
    message.keyId = object.keyId ?? new Uint8Array(0);
    message.key = object.key ?? new Uint8Array(0);
    message.fromCounter = object.fromCounter ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
