// row-menu.tsx — what a session row in the list offers besides opening it: pin it to the top, and delete it (behind a
// confirmation). The `⋮` arrives with the pointer, because it belongs to the row being read rather than being
// something you go looking for; on a touch screen, which cannot hover, it is always there.
//
// RENAME is deliberately absent. A title is the runtime's (generated by a side call and stored with the session), and
// a rename kept on this device would give one session two names on two screens. It arrives with a `session.rename`
// command, and not before.
import { signal } from "@preact/signals";
import { useEffect, useRef, useState } from "preact/hooks";
import type { RuntimeInfo, SessionSummary } from "../session-host";
import { IconMore, IconPin, IconTrash } from "../sidebar/icons";
import { truncate } from "../sidebar/format";
import type { ChatStore } from "./chat-store";
import { mayCommand } from "./grants";
import { dropPin, pinned, togglePin } from "./view-mode";

/** The session a delete is waiting to be confirmed for, or null. One at a time, drawn by `DeleteConfirm`. */
const confirming = signal<{ s: SessionSummary; rt: RuntimeInfo; title: string } | null>(null);

/** Can this device delete this session: the runtime is reachable, and this client holds the grant to ask. */
export function mayDelete(rt: RuntimeInfo): boolean {
    return rt.online && mayCommand(rt, "session.delete");
}

/** A row's `⋮` and the small menu it opens. The menu is placed FIXED from the button's own rect, because the list
 *  scrolls and clips, and a menu on the last row would otherwise open into nothing. */
export function RowMenu({ s, rt, title }: { s: SessionSummary; rt: RuntimeInfo; title: string }) {
    const key = `${s.id.runtime}:${s.id.hash}`;
    const [at, setAt] = useState<{ top: number; left: number; up: boolean } | null>(null);
    const btn = useRef<HTMLButtonElement>(null);
    const isPinned = pinned.value.has(key);
    useEffect(() => {
        if (!at) return;
        const close = () => setAt(null);
        const onDown = (e: Event) => { if (!(e.target as HTMLElement)?.closest?.(".chat-row-menu, .chat-row-more")) close(); };
        const onKey = (e: KeyboardEvent) => { if (e.key === "Escape") { close(); btn.current?.focus(); } };
        document.addEventListener("pointerdown", onDown);
        document.addEventListener("keydown", onKey);
        window.addEventListener("resize", close);
        // The list scrolling under an open menu would leave it pointing at a different row.
        document.addEventListener("scroll", close, true);
        return () => {
            document.removeEventListener("pointerdown", onDown);
            document.removeEventListener("keydown", onKey);
            window.removeEventListener("resize", close);
            document.removeEventListener("scroll", close, true);
        };
    }, [at]);
    const open = () => {
        const r = btn.current?.getBoundingClientRect();
        if (!r) return;
        const up = r.bottom + 110 > window.innerHeight;   // not enough room below: open upwards
        setAt({ top: up ? r.top - 4 : r.bottom + 4, left: Math.max(8, r.right - 180), up });
    };
    const act = (run: () => void) => { setAt(null); run(); };
    return (
        <>
            <button ref={btn} class={`chat-row-more hbtn${at ? " on" : ""}`} aria-label={`Options for ${truncate(title, 60)}`}
                aria-haspopup="menu" aria-expanded={!!at} onClick={(e) => { e.stopPropagation(); if (at) setAt(null); else open(); }}>
                <IconMore />
            </button>
            {at ? (
                <div class={`chat-row-menu menu${at.up ? " up" : ""}`} role="menu" style={`top:${at.top}px;left:${at.left}px`}>
                    <button class="menu-item" role="menuitem" onClick={() => act(() => togglePin(key))}>
                        <IconPin />{isPinned ? "Unpin" : "Pin to the top"}
                    </button>
                    {mayDelete(rt) ? (
                        <button class="menu-item danger" role="menuitem" onClick={() => act(() => { confirming.value = { s, rt, title }; })}>
                            <IconTrash />Delete…
                        </button>
                    ) : null}
                </div>
            ) : null}
        </>
    );
}

/** The one confirmation a delete goes through, mounted once by the page. Deleting cannot be undone — the runtime drops
 *  the transcript from its own storage — so it asks, names the session, and puts the focus on Cancel. */
export function DeleteConfirm({ store }: { store: ChatStore }) {
    const c = confirming.value;
    const [busy, setBusy] = useState(false);
    const cancel = useRef<HTMLButtonElement>(null);
    useEffect(() => {
        if (!c) return;
        setBusy(false);
        cancel.current?.focus();
        const onKey = (e: KeyboardEvent) => { if (e.key === "Escape") confirming.value = null; };
        document.addEventListener("keydown", onKey);
        return () => document.removeEventListener("keydown", onKey);
    }, [c]);
    if (!c) return null;
    const key = `${c.s.id.runtime}:${c.s.id.hash}`;
    const go = async () => {
        setBusy(true);
        const r = await store.send({ type: "session.delete", session: c.s.id });
        // A failure is already a notice (ChatStore.send); the dialog closes either way rather than sitting on an error.
        if (r.ok) dropPin(key);
        confirming.value = null;
    };
    return (
        <div class="chat-dialog-back" onPointerDown={(e) => { if (e.target === e.currentTarget) confirming.value = null; }}>
            <div class="chat-dialog" role="alertdialog" aria-modal="true" aria-labelledby="chat-del-h" aria-describedby="chat-del-p">
                <h2 id="chat-del-h">Delete this session?</h2>
                <p id="chat-del-p"><b>{truncate(c.title, 80)}</b> and its transcript will be removed from {c.rt.name}. This cannot be undone.</p>
                <div class="chat-dialog-actions">
                    <button ref={cancel} class="btn" onClick={() => (confirming.value = null)}>Cancel</button>
                    <button class="btn danger" disabled={busy} onClick={go}>{busy ? "Deleting…" : "Delete"}</button>
                </div>
            </div>
        </div>
    );
}
