// row-menu.tsx — what a session row in the list offers besides opening it: pin it to the top, and delete it (behind a
// confirmation). The `⋮` arrives with the pointer, because it belongs to the row being read rather than being
// something you go looking for; on a touch screen, which cannot hover, it is always there.
//
// RENAME is deliberately absent. A title is the runtime's (generated by a side call and stored with the session), and
// a rename kept on this device would give one session two names on two screens. It arrives with a `session.rename`
// command, and not before.
import { signal } from "@preact/signals";
import { useEffect, useRef, useState } from "preact/hooks";
import type { RuntimeInfo, SessionSummary } from "../session-host";
import { IconMore, IconPin, IconTrash } from "../sidebar/icons";
import { truncate } from "../sidebar/format";
import type { ChatStore } from "./chat-store";
import { mayCommand } from "./grants";
import { MenuItem } from "./menu";
import { addPin, dropPin, pinned } from "./view-mode";

/** Which row's menu is open, and where: ONE for the whole list, so opening a second closes the first. Local state per
 *  row let every `⋮` think it was the only one, and a click on another row's `⋮` counted as a click inside a menu. */
const openMenu = signal<{ key: string; top: number; left: number; up: boolean } | null>(null);

/** The session a delete is waiting to be confirmed for, or null. One at a time, drawn by `DeleteConfirm`. */
const confirming = signal<{ s: SessionSummary; rt: RuntimeInfo; title: string } | null>(null);

/** Can this device delete this session: the runtime is reachable, and this client holds the grant to ask. */
export function mayDelete(rt: RuntimeInfo): boolean {
    return rt.online && mayCommand(rt, "session.delete");
}

/**
 * Is this session pinned? This device's pin, or the runtime's: a pin made on the phone is a pin here too, and a pin
 * the runtime holds is what keeps the session from being expired or evicted (`session.pin`).
 */
export function isPinned(s: SessionSummary): boolean {
    return pinned.value.has(`${s.id.runtime}:${s.id.hash}`) || !!s.pinned;
}

/**
 * Pin or unpin: this device's copy (which orders the Pinned section) at once, and the runtime's where it can take
 * one, which is the pin that keeps the session. The runtime's answer is not assumed: the row's `pinned` changes when
 * its upsert arrives. A runtime past its pin limit refuses with `conflict` (said as a notice by the store), and the
 * device's pin is taken back so the list does not claim a pin the runtime refused. A runtime with no `session.pin`
 * keeps the device's pin alone, as before it existed.
 */
async function setPin(store: ChatStore, s: SessionSummary, rt: RuntimeInfo, on: boolean): Promise<void> {
    const key = `${s.id.runtime}:${s.id.hash}`;
    if (on) addPin(key); else dropPin(key);
    if (!rt.online || !mayCommand(rt, "session.pin")) return;
    const r = await store.send({ type: "session.pin", session: s.id, pinned: on });
    if (!r.ok && on && r.error.code !== "unsupported") dropPin(key);
}

/** A row's `⋮` and the small menu it opens. The menu is placed FIXED from the button's own rect, because the list
 *  scrolls and clips, and a menu on the last row would otherwise open into nothing. */
export function RowMenu({ store, s, rt, title }: { store: ChatStore; s: SessionSummary; rt: RuntimeInfo; title: string }) {
    const key = `${s.id.runtime}:${s.id.hash}`;
    const m = openMenu.value;
    const at = m?.key === key ? m : null;
    const setAt = (v: { top: number; left: number; up: boolean } | null) => { openMenu.value = v ? { key, ...v } : (openMenu.value?.key === key ? null : openMenu.value); };
    const btn = useRef<HTMLButtonElement>(null);
    const menu = useRef<HTMLDivElement>(null);
    const pinnedNow = isPinned(s);
    useEffect(() => {
        if (!at) return;
        const close = () => setAt(null);
        // Anywhere but this menu and its own button closes it; another row's `⋮` then opens its own.
        const onDown = (e: Event) => { const t = e.target as Node; if (!menu.current?.contains(t) && !btn.current?.contains(t)) close(); };
        const onKey = (e: KeyboardEvent) => { if (e.key === "Escape") { close(); btn.current?.focus(); } };
        document.addEventListener("pointerdown", onDown);
        document.addEventListener("keydown", onKey);
        window.addEventListener("resize", close);
        // The list scrolling under an open menu would leave it pointing at a different row.
        document.addEventListener("scroll", close, true);
        return () => {
            document.removeEventListener("pointerdown", onDown);
            document.removeEventListener("keydown", onKey);
            window.removeEventListener("resize", close);
            document.removeEventListener("scroll", close, true);
        };
    }, [!!at]);
    const open = () => {
        const r = btn.current?.getBoundingClientRect();
        if (!r) return;
        const up = r.bottom + 110 > window.innerHeight;   // not enough room below: open upwards
        setAt({ top: up ? r.top - 4 : r.bottom + 4, left: Math.max(8, r.right - 190), up });
    };
    const act = (run: () => void) => { setAt(null); run(); };
    return (
        <>
            <button ref={btn} class={`chat-row-more hbtn${at ? " on" : ""}`} aria-label={`Options for ${truncate(title, 60)}`}
                aria-haspopup="menu" aria-expanded={!!at} onClick={(e) => { e.stopPropagation(); if (at) setAt(null); else open(); }}>
                <IconMore />
            </button>
            {at ? (
                <div ref={menu} class={`chat-menu chat-row-menu${at.up ? " up" : ""}`} role="menu" style={`top:${at.top}px;left:${at.left}px`}>
                    <MenuItem icon={<IconPin />} label={pinnedNow ? "Unpin" : "Pin to the top"} onPick={() => act(() => void setPin(store, s, rt, !pinnedNow))} />
                    {mayDelete(rt) ? <MenuItem icon={<IconTrash />} label="Delete…" onPick={() => act(() => { confirming.value = { s, rt, title }; })} /> : null}
                </div>
            ) : null}
        </>
    );
}

/** The one confirmation a delete goes through, mounted once by the page. Deleting cannot be undone — the runtime drops
 *  the transcript from its own storage — so it asks, names the session, and puts the focus on Cancel. */
export function DeleteConfirm({ store }: { store: ChatStore }) {
    const c = confirming.value;
    const [busy, setBusy] = useState(false);
    const cancel = useRef<HTMLButtonElement>(null);
    useEffect(() => {
        if (!c) return;
        setBusy(false);
        cancel.current?.focus();
        const onKey = (e: KeyboardEvent) => { if (e.key === "Escape") confirming.value = null; };
        document.addEventListener("keydown", onKey);
        return () => document.removeEventListener("keydown", onKey);
    }, [c]);
    if (!c) return null;
    const key = `${c.s.id.runtime}:${c.s.id.hash}`;
    const go = async () => {
        setBusy(true);
        const r = await store.send({ type: "session.delete", session: c.s.id });
        // A failure is already a notice (ChatStore.send); the dialog closes either way rather than sitting on an error.
        if (r.ok) dropPin(key);
        confirming.value = null;
    };
    return (
        <div class="chat-dialog-back" onPointerDown={(e) => { if (e.target === e.currentTarget) confirming.value = null; }}>
            <div class="chat-dialog" role="alertdialog" aria-modal="true" aria-labelledby="chat-del-h" aria-describedby="chat-del-p">
                <h2 id="chat-del-h">Delete this session?</h2>
                <p id="chat-del-p"><b>{truncate(c.title, 80)}</b> and its transcript will be removed from {c.rt.name}. This cannot be undone.</p>
                <div class="chat-dialog-actions">
                    <button ref={cancel} class="btn" onClick={() => (confirming.value = null)}>Cancel</button>
                    <button class="btn primary" disabled={busy} onClick={go}>{busy ? "Deleting…" : "Delete"}</button>
                </div>
            </div>
        </div>
    );
}
