// sync-embed.mjs — PUT THE WEB PAGE INTO THE APP: the page the WebView loads (dist-native/, built by the repo's
// scripts/build-web.mjs) becomes `src/generated/embed.ts`, a string the app writes to its own storage at startup. So the
// page ships inside the app's bundle and its version is always the app's (docs/spec/NATIVE_SHELL.md).
//
//   node scripts/sync-embed.mjs           # the real page: this device's account over the hub
//   node scripts/sync-embed.mjs --demo    # the demo world instead (fake host, no hub): for building and screenshots only
//
// The fonts the page's stylesheet names (KaTeX) travel as base64 beside it and are written next to it.
//
// It also writes `src/generated/build.ts`: which commit this app is and which repository publishes its builds, for the
// update check (src/native/app-update.ts). The repository is CI's `GITHUB_REPOSITORY`, so a fork's app checks the fork,
// and a local build names none and never checks. `WML_UPDATE_REPO`, `WML_UPDATE_API`, `WML_UPDATE_SHA` and
// `WML_UPDATE_COMMITTED_AT` override each part, to point an emulator at tests/fixtures/fake-github.mjs.

import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

const HERE = path.resolve(import.meta.dirname, "..");
const DIST = path.resolve(HERE, "..", "dist-native");
const demo = process.argv.includes("--demo");
const page = path.join(DIST, demo ? "embed-demo.html" : "embed.html");
if (!existsSync(page)) {
    console.error(`✗ ${path.relative(HERE, page)} is missing: run \`node scripts/build-web.mjs\` in the repo root first.`);
    process.exit(1);
}
const html = readFileSync(page, "utf8");
const fontsDir = path.join(DIST, "fonts");
const fonts = existsSync(fontsDir) ? Object.fromEntries(readdirSync(fontsDir).map((f) => [f, readFileSync(path.join(fontsDir, f)).toString("base64")])) : {};
const id = html.length.toString(36) + "-" + [...html].reduce((h, c) => (h * 31 + c.charCodeAt(0)) >>> 0, 7).toString(36);
mkdirSync(path.join(HERE, "src", "generated"), { recursive: true });
writeFileSync(path.join(HERE, "src", "generated", "embed.ts"), `// GENERATED by scripts/sync-embed.mjs from dist-native/${path.basename(page)}; do not edit, do not commit.

/** The WebView's page: its HTML, a content id (rewritten only when it changes), the fonts beside it, and whether it is the demo. */
export const EMBED = ${JSON.stringify({ id, demo, html, fonts })} as const;
`);
console.log(`✓ src/generated/embed.ts: ${demo ? "the DEMO page" : "the page"}, ${(html.length / 1e6).toFixed(2)} MB, ${Object.keys(fonts).length} fonts`);

/** A git answer from the repo root, or null outside a checkout. */
const git = (...args) => { try { return execFileSync("git", args, { cwd: path.resolve(HERE, ".."), encoding: "utf8" }).trim() || null; } catch { return null; } };
const env = (k) => (process.env[k] === undefined ? undefined : process.env[k] || null);
// The demo page is for screenshots and never ships, so it checks only when told to.
const build = {
    repo: env("WML_UPDATE_REPO") ?? (demo ? null : env("GITHUB_REPOSITORY") ?? null),
    sha: env("WML_UPDATE_SHA") ?? git("rev-parse", "HEAD"),
    committedAt: env("WML_UPDATE_COMMITTED_AT") ?? git("log", "-1", "--format=%cI"),
    api: env("WML_UPDATE_API") ?? "https://api.github.com",
    tag: "android-latest",
};
writeFileSync(path.join(HERE, "src", "generated", "build.ts"), `// GENERATED by scripts/sync-embed.mjs; do not edit, do not commit.
import type { BuildInfo } from "../../../src/native/app-update";

/** This app's commit and where newer builds are published (src/native/app-update.ts). */
export const BUILD: BuildInfo = ${JSON.stringify(build)};
`);
console.log(`✓ src/generated/build.ts: ${build.sha?.slice(0, 7) ?? "no commit"}, ${build.repo ? `checks ${build.repo}` : "no repository: the update check is off"}`);
