// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.1
//   protoc               v7.35.1
// source: chat.proto

/* eslint-disable */
import { BinaryReader } from "@bufbuild/protobuf/wire";

export const protobufPackage = "slop.chat.v1";

/** Sent once, before any Delta. These are the fields OpenAI repeats per chunk. */
export interface Start {
  id: string;
  model: string;
  created: number;
  systemFingerprint: string;
  /** "assistant" */
  role: string;
}

/**
 * One token, or one step of one. Every field is optional -- proto3 has no other kind -- so
 * a plain text delta costs a tag, a length and its bytes, and carries nothing for the rest.
 */
export interface Delta {
  content: string;
  reasoning: string;
  /**
   * Present only on the chunks that carry them. A tool call arrives in pieces: the first
   * chunk for an index names the function, later ones append to arguments.
   */
  toolCalls: ToolCall[];
  /** Present only when the request asked for logprobs. */
  logprobs: Logprob[];
}

export interface ToolCall {
  id: string;
  index: number;
  /** "function" */
  type: string;
  function: FunctionMessage | undefined;
}

export interface FunctionMessage {
  name: string;
  /** a JSON fragment, streamed in pieces */
  arguments: string;
}

/**
 * One position in the output. Bytes is the token's raw representation, which is how a
 * client reassembles text a token boundary splits in the middle of a character.
 */
export interface TokenLogprob {
  token: string;
  logprob: number;
  bytes: number[];
}

export interface Logprob {
  token: TokenLogprob | undefined;
  topLogprobs: TokenLogprob[];
}

/** Sent once, after the last Delta. */
export interface End {
  finishReason: string;
  promptTokens: number;
  completionTokens: number;
}

export interface Frame {
  start?: Start | undefined;
  delta?: Delta | undefined;
  end?: End | undefined;
}

function createBaseStart(): Start {
  return { id: "", model: "", created: 0, systemFingerprint: "", role: "" };
}

export const Start: MessageFns<Start> = {
  decode(input: BinaryReader | Uint8Array, length?: number): Start {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseStart();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.id = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.model = reader.string();
            continue;
          }
          case 3: {
            if (tag !== 24) {
              break;
            }

            message.created = longToNumber(reader.uint64());
            continue;
          }
          case 4: {
            if (tag !== 34) {
              break;
            }

            message.systemFingerprint = reader.string();
            continue;
          }
          case 5: {
            if (tag !== 42) {
              break;
            }

            message.role = reader.string();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create<I extends Exact<DeepPartial<Start>, I>>(base?: I): Start {
    return Start.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Start>, I>>(object: I): Start {
    const message = createBaseStart();
    message.id = object.id ?? "";
    message.model = object.model ?? "";
    message.created = object.created ?? 0;
    message.systemFingerprint = object.systemFingerprint ?? "";
    message.role = object.role ?? "";
    return message;
  },
};

function createBaseDelta(): Delta {
  return { content: "", reasoning: "", toolCalls: [], logprobs: [] };
}

export const Delta: MessageFns<Delta> = {
  decode(input: BinaryReader | Uint8Array, length?: number): Delta {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseDelta();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.content = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.reasoning = reader.string();
            continue;
          }
          case 3: {
            if (tag !== 26) {
              break;
            }

            message.toolCalls.push(ToolCall.decode(reader, reader.uint32()));
            continue;
          }
          case 4: {
            if (tag !== 34) {
              break;
            }

            message.logprobs.push(Logprob.decode(reader, reader.uint32()));
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create<I extends Exact<DeepPartial<Delta>, I>>(base?: I): Delta {
    return Delta.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Delta>, I>>(object: I): Delta {
    const message = createBaseDelta();
    message.content = object.content ?? "";
    message.reasoning = object.reasoning ?? "";
    message.toolCalls = object.toolCalls?.map((e) => ToolCall.fromPartial(e)) || [];
    message.logprobs = object.logprobs?.map((e) => Logprob.fromPartial(e)) || [];
    return message;
  },
};

function createBaseToolCall(): ToolCall {
  return { id: "", index: 0, type: "", function: undefined };
}

export const ToolCall: MessageFns<ToolCall> = {
  decode(input: BinaryReader | Uint8Array, length?: number): ToolCall {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseToolCall();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.id = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 16) {
              break;
            }

            message.index = reader.uint32();
            continue;
          }
          case 3: {
            if (tag !== 26) {
              break;
            }

            message.type = reader.string();
            continue;
          }
          case 4: {
            if (tag !== 34) {
              break;
            }

            message.function = FunctionMessage.decode(reader, reader.uint32());
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create<I extends Exact<DeepPartial<ToolCall>, I>>(base?: I): ToolCall {
    return ToolCall.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ToolCall>, I>>(object: I): ToolCall {
    const message = createBaseToolCall();
    message.id = object.id ?? "";
    message.index = object.index ?? 0;
    message.type = object.type ?? "";
    message.function = (object.function !== undefined && object.function !== null)
      ? FunctionMessage.fromPartial(object.function)
      : undefined;
    return message;
  },
};

function createBaseFunctionMessage(): FunctionMessage {
  return { name: "", arguments: "" };
}

export const FunctionMessage: MessageFns<FunctionMessage> = {
  decode(input: BinaryReader | Uint8Array, length?: number): FunctionMessage {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseFunctionMessage();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.name = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.arguments = reader.string();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create<I extends Exact<DeepPartial<FunctionMessage>, I>>(base?: I): FunctionMessage {
    return FunctionMessage.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<FunctionMessage>, I>>(object: I): FunctionMessage {
    const message = createBaseFunctionMessage();
    message.name = object.name ?? "";
    message.arguments = object.arguments ?? "";
    return message;
  },
};

function createBaseTokenLogprob(): TokenLogprob {
  return { token: "", logprob: 0, bytes: [] };
}

export const TokenLogprob: MessageFns<TokenLogprob> = {
  decode(input: BinaryReader | Uint8Array, length?: number): TokenLogprob {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseTokenLogprob();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.token = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 17) {
              break;
            }

            message.logprob = reader.double();
            continue;
          }
          case 3: {
            if (tag === 24) {
              message.bytes.push(reader.uint32());

              continue;
            }

            if (tag === 26) {
              const end2 = reader.uint32() + reader.pos;
              while (reader.pos < end2) {
                message.bytes.push(reader.uint32());
              }

              continue;
            }

            break;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create<I extends Exact<DeepPartial<TokenLogprob>, I>>(base?: I): TokenLogprob {
    return TokenLogprob.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TokenLogprob>, I>>(object: I): TokenLogprob {
    const message = createBaseTokenLogprob();
    message.token = object.token ?? "";
    message.logprob = object.logprob ?? 0;
    message.bytes = object.bytes?.map((e) => e) || [];
    return message;
  },
};

function createBaseLogprob(): Logprob {
  return { token: undefined, topLogprobs: [] };
}

export const Logprob: MessageFns<Logprob> = {
  decode(input: BinaryReader | Uint8Array, length?: number): Logprob {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseLogprob();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.token = TokenLogprob.decode(reader, reader.uint32());
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.topLogprobs.push(TokenLogprob.decode(reader, reader.uint32()));
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create<I extends Exact<DeepPartial<Logprob>, I>>(base?: I): Logprob {
    return Logprob.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Logprob>, I>>(object: I): Logprob {
    const message = createBaseLogprob();
    message.token = (object.token !== undefined && object.token !== null)
      ? TokenLogprob.fromPartial(object.token)
      : undefined;
    message.topLogprobs = object.topLogprobs?.map((e) => TokenLogprob.fromPartial(e)) || [];
    return message;
  },
};

function createBaseEnd(): End {
  return { finishReason: "", promptTokens: 0, completionTokens: 0 };
}

export const End: MessageFns<End> = {
  decode(input: BinaryReader | Uint8Array, length?: number): End {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseEnd();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.finishReason = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 16) {
              break;
            }

            message.promptTokens = reader.uint32();
            continue;
          }
          case 3: {
            if (tag !== 24) {
              break;
            }

            message.completionTokens = reader.uint32();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create<I extends Exact<DeepPartial<End>, I>>(base?: I): End {
    return End.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<End>, I>>(object: I): End {
    const message = createBaseEnd();
    message.finishReason = object.finishReason ?? "";
    message.promptTokens = object.promptTokens ?? 0;
    message.completionTokens = object.completionTokens ?? 0;
    return message;
  },
};

function createBaseFrame(): Frame {
  return { start: undefined, delta: undefined, end: undefined };
}

export const Frame: MessageFns<Frame> = {
  decode(input: BinaryReader | Uint8Array, length?: number): Frame {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseFrame();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.start = Start.decode(reader, reader.uint32());
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.delta = Delta.decode(reader, reader.uint32());
            continue;
          }
          case 3: {
            if (tag !== 26) {
              break;
            }

            message.end = End.decode(reader, reader.uint32());
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create<I extends Exact<DeepPartial<Frame>, I>>(base?: I): Frame {
    return Frame.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Frame>, I>>(object: I): Frame {
    const message = createBaseFrame();
    message.start = (object.start !== undefined && object.start !== null) ? Start.fromPartial(object.start) : undefined;
    message.delta = (object.delta !== undefined && object.delta !== null) ? Delta.fromPartial(object.delta) : undefined;
    message.end = (object.end !== undefined && object.end !== null) ? End.fromPartial(object.end) : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

export interface MessageFns<T> {
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
