// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.1
//   protoc               v7.35.1
// source: events.proto

/* eslint-disable */

export const protobufPackage = "slop.events.v1";

/** The measured machine: what each device does, and what each link costs. */
export interface BoxProfile {
  state?: string | undefined;
  measured_at?: string | undefined;
  devices: ProfileDevice[];
  links: ProfileLink[];
  failures: ProfileFailure[];
}

/** The machine's compute: what can be used, what cannot, and how it is wired. */
export interface ComputeInfo {
  system_compute?: SystemComputeInfo | undefined;
  supported_gpus: GPUInfo[];
  unavailable_gpus: UnavailableGPU[];
  topology?: GPUTopology | undefined;
  profile?: BoxProfile | undefined;
}

/** The box profile's prediction for this generation's decode, made before it ran. */
export interface DecodePrediction {
  ms_per_token?: number | undefined;
  occupancy_tokens?: number | undefined;
  basis?: string | undefined;
  profile_ms_per_token: number;
  correction_factor: number;
  correction_samples: number;
  excludes_cache_read: boolean;
}

/**
 * One line of /api/events.
 *
 * Flat, because that is what is sent: the server builds this from api.EventFrame, which
 * repeats ModelEvent's fields rather than embedding it. Most fields are absent on most
 * kinds; which ones a kind carries is in the kind list at the top of this file.
 */
export interface EventFrame {
  /** Frame version; 1. See VERSIONING at the top of this file. */
  v?: number | undefined;
  kind?:
    | string
    | undefined;
  /** Milliseconds since this connection's hello. Negative on backfilled frames. */
  t?: number | undefined;
  unavailable_gpus: UnavailableGPU[];
  serverTime?:
    | string
    | undefined;
  /** Identifies the machine, so a client can drop history from a different one. hello only. */
  box: string;
  /** How much backfill this server can serve. hello only. */
  retainedMs: number;
  /** How many retained frames follow this hello. Present on every hello, including as 0. */
  backfilled?: number | undefined;
  model: string;
  reason: string;
  expires_at?: string | undefined;
  duration_ms: number;
  /** The two halves of a load, repeated on load.complete so a client that */
  weights_ms: number;
  /** subscribed mid-load still gets the split. */
  context_ms: number;
  /** On load.weights what the weights occupy; on load.complete what the finished model holds. */
  size_vram: number;
  timings?: GenerationTimings | undefined;
  hint?: RequestHint | undefined;
  predicted_decode?: DecodePrediction | undefined;
  shape?: RequestShape | undefined;
  lease?: LeaseInfo | undefined;
  memory?: MemoryBreakdown | undefined;
  memory_host?: MemoryBreakdown | undefined;
  weights_on_disk: number;
  /** Which layers went where, when the server records that. */
  placement?: ModelPlacement | undefined;
  estimate?:
    | LoadEstimate
    | undefined;
  /** What the load holds everywhere, device and host. Above size_vram means it spilled. */
  size_total: number;
  /** The /api/ps body, on a sample. */
  ps?:
    | ProcessResponse
    | undefined;
  /** The /api/info body, on the first sample and whenever it changed. */
  info?:
    | InfoResponse
    | undefined;
  /**
   * Frames this subscriber lost to a full buffer, cumulative. Non-zero means its record has a
   * gap, which must not be drawn as a flat line. Absent means none.
   */
  dropped: number;
}

/** The decode speed this model is expected to reach on this placement. */
export interface ExpectedDecode {
  unavailable: string;
  tokens_per_sec: number;
  basis: string;
  profile_tokens_per_sec: number;
  correction_factor: number;
  correction_samples: number;
  ms_per_token_per_1k_context: number;
  active_weights_fraction: number;
}

/** What the PCI bus says about a card that the driver no longer answers for. */
export interface GPUBusState {
  present?: boolean | undefined;
  link_speed: string;
  link_width: number;
  power_state: string;
  max_link_speed: string;
  max_link_width: number;
  pcie_fatal_errors?: number | undefined;
  pcie_nonfatal_errors?: number | undefined;
}

/** One usable GPU. */
export interface GPUInfo {
  gpu_id?: string | undefined;
  pci_id: string;
  name?: string | undefined;
  description: string;
  total_memory?: number | undefined;
  processes: GPUProcess[];
  processes_scope: string;
  leased: string;
  physical_memory: number;
  memory_bandwidth_bytes_per_sec: number;
  memory_bus_width_bits: number;
  memory_clock_max_mhz: number;
  pcie_max_generation: number;
  pcie_max_width: number;
  utilization?: GPUUtilization | undefined;
  free_memory?: number | undefined;
  compute: string;
  driver: string;
  runner?: string | undefined;
}

/** One link between two GPUs. */
export interface GPULink {
  a?: string | undefined;
  b?: string | undefined;
  type?: string | undefined;
  path: string;
  nvlink_count: number;
  nvlink_version: number;
  pcie_path: string;
  bandwidth_bytes_per_sec: number;
  bandwidth_source: string;
  reason: string;
}

/** A process holding memory on a device. */
export interface GPUProcess {
  pid?: number | undefined;
  used_memory?: number | undefined;
  name: string;
  runner?: GPUProcessRunner | undefined;
  ollama_helper: boolean;
}

/** The model an ollama runner process is serving, when the process is one. */
export interface GPUProcessRunner {
  model?: string | undefined;
  loading: boolean;
}

/** How the GPUs are connected to each other. */
export interface GPUTopology {
  status?: string | undefined;
  detail: string;
  gpus: string[];
  links: GPULink[];
}

/** A device's utilization, as the driver reports it. */
export interface GPUUtilization {
  gpu_percent?: number | undefined;
  memory_percent?: number | undefined;
}

/** How one generation divided, from the engine's own measurement, on gen.end. */
export interface GenerationTimings {
  prompt_tokens?:
    | number
    | undefined;
  /** Of prompt_tokens, how many the cache already held. */
  prompt_tokens_cached?: number | undefined;
  prompt_ms?: number | undefined;
  eval_ms?: number | undefined;
  decoded?: number | undefined;
  prompt_cache_swap?: PromptCacheSwap | undefined;
}

/** The /api/info body. Sent on the first sample and whenever it has changed. */
export interface InfoResponse {
  version?: string | undefined;
  models?: SystemModelInfo | undefined;
  compute?: ComputeInfo | undefined;
  load_stall_timeout_ms?: number | undefined;
}

/** Who holds a GPU lease, and on which devices. */
export interface LeaseInfo {
  holder?: string | undefined;
  devices: string[];
}

/** A measured all-reduce over that link. */
export interface LinkReduction {
  width?: number | undefined;
  us?: number | undefined;
}

/** What a load was predicted to need, and what the prediction was based on. */
export interface LoadEstimate {
  /** What the model itself was expected to hold. */
  predicted?:
    | number
    | undefined;
  /** Plus the batch surcharge: the figure the fit decision was made against. */
  predicted_for_load?:
    | number
    | undefined;
  /** Where the figure came from: metadata, calibration or probe. Read this first. */
  source?: string | undefined;
  num_ctx?: number | undefined;
  num_gpu?: number | undefined;
  num_batch?: number | undefined;
  metadata_complete?:
    | boolean
    | undefined;
  /**
   * UNSTABLE, and only weights and kv_cache are populated. It is always the METADATA split even
   * when source says probe or calibration, so its terms are comparable with what load.complete
   * measured but its total is not `predicted`.
   */
  breakdown?: MemoryBreakdown | undefined;
}

/** What a load's memory holds, split by kind. */
export interface MemoryBreakdown {
  weights?: number | undefined;
  kv_cache?: number | undefined;
  recurrent_state: number;
  compute?: number | undefined;
  output: number;
  projector: number;
  other: number;
}

/** The model's own description, from its manifest. */
export interface ModelDetails {
  parent_model?: string | undefined;
  format?: string | undefined;
  family?: string | undefined;
  families: string[];
  parameter_size?: string | undefined;
  quantization_level?: string | undefined;
  context_length: number;
  embedding_length: number;
}

/**
 * Which layers landed on which device. Absent unless the server was started with
 * OLLAMA_LAYER_PLACEMENT.
 */
export interface ModelPlacement {
  num_layers?: number | undefined;
  devices: PlacementRange[];
  swa_layers: number[];
}

/** The ceiling the hardware puts on decode for this model, and what it was computed from. */
export interface ModelRoofline {
  unavailable: string;
  basis: string;
  bytes_per_token: number;
  ceiling_tokens_per_sec: number;
  kv_bytes_per_context_token: number;
  devices: RooflineDevice[];
}

/** One device's share of the layers, as a contiguous range. */
export interface PlacementRange {
  device?: string | undefined;
  gpu_id: string;
  first_layer?: number | undefined;
  last_layer?: number | undefined;
  layers?: number | undefined;
}

/** One model's share of one device. */
export interface ProcessGPU {
  gpu_id?: string | undefined;
  runner: string;
  size_vram?: number | undefined;
  memory?: MemoryBreakdown | undefined;
}

/** One resident model, as /api/ps reports it. */
export interface ProcessModelResponse {
  name?: string | undefined;
  busy: boolean;
  state: string;
  model?: string | undefined;
  size?: number | undefined;
  digest?: string | undefined;
  details: ModelDetails | undefined;
  expires_at?: string | undefined;
  size_vram?: number | undefined;
  roofline?: ModelRoofline | undefined;
  expected_decode?: ExpectedDecode | undefined;
  context_length?: number | undefined;
  memory?: MemoryBreakdown | undefined;
  weights_on_disk: number;
  placement?:
    | ModelPlacement
    | undefined;
  /** UNSTABLE. Absent means the runner could not be asked, which is NOT the same as idle. */
  activity?:
    | RunnerActivity
    | undefined;
  /** Per device. Absent means the model is on the host, not that the split is unknown. */
  gpus: ProcessGPU[];
}

/** The /api/ps body, byte-identical to what that endpoint serves. */
export interface ProcessResponse {
  models: ProcessModelResponse[];
}

/** One device's measured bandwidth and per-layer cost. */
export interface ProfileDevice {
  gpu_id?: string | undefined;
  pci_id: string;
  bandwidth_bytes_per_sec?: number | undefined;
  token_overhead_ms?: number | undefined;
  layer_overhead_us?: number | undefined;
  fit_error_pct?: number | undefined;
}

/** A measurement the profile could not take, and why. */
export interface ProfileFailure {
  what?: string | undefined;
  pci_ids: string[];
  error?: string | undefined;
}

/** One link's measured cost, as the profile saw it. */
export interface ProfileLink {
  pci_ids: string[];
  reductions: LinkReduction[];
}

/** What the runner's prompt cache holds. */
export interface PromptCacheState {
  entries?: number | undefined;
  tokens?: number | undefined;
  bytes?: number | undefined;
  limit_bytes?: number | undefined;
}

/** What the prompt cache did for this generation: what it saved, and what it cost. */
export interface PromptCacheSwap {
  ms?: number | undefined;
  saved_tokens: number;
  saved_bytes: number;
  restored?: boolean | undefined;
  evicted: number;
  evicted_bytes: number;
  too_large: boolean;
}

/** What the caller said the request was for. Advisory, and recorded only. */
export interface RequestHint {
  use: string;
  session: string;
  request: string;
  after: string;
  synthetic: boolean;
}

/** The request's form -- not its content. Nothing here is derived from the prompt. */
export interface RequestShape {
  endpoint?: string | undefined;
  surface?: string | undefined;
  stream?: boolean | undefined;
  messages: number;
  images: number;
  tools: number;
  format: boolean;
  think: string;
  num_ctx?: number | undefined;
  num_gpu?: number | undefined;
  num_predict?: number | undefined;
  keep_alive_s?: number | undefined;
  client: string;
}

/** One device's contribution to the roofline. */
export interface RooflineDevice {
  gpu_id?: string | undefined;
  pci_id: string;
  bytes_per_token?: number | undefined;
  kv_bytes_per_context_token: number;
  memory_bandwidth_bytes_per_sec?: number | undefined;
}

/**
 * What the runner is doing right now.
 *
 * UNSTABLE: this is the live edge of the work and has changed several times. Generate from
 * it, but expect fields to be added.
 */
export interface RunnerActivity {
  phase?: string | undefined;
  slots?: number | undefined;
  slots_busy?: number | undefined;
  prompt_tokens: number;
  prompt_tokens_done: number;
  prompt_tokens_cached: number;
  decoded: number;
  prompt_cache?: PromptCacheState | undefined;
}

/** Host memory and CPU, as the machine reports them. */
export interface SystemComputeInfo {
  cpu_cores?: number | undefined;
  total_memory?: number | undefined;
  free_memory?: number | undefined;
  free_swap?: number | undefined;
}

/** How many models are on disk and how many are resident. */
export interface SystemModelInfo {
  store?: string | undefined;
  count?: number | undefined;
  filesystem_used?: number | undefined;
  running?: number | undefined;
  vram_used?: number | undefined;
}

/**
 * A GPU the machine has and cannot use.
 *
 * On the hello frame rather than only on an edge, because the fault is almost always OLDER
 * than the connection: hardware does not wait for a subscriber. Transitions arrive later as
 * an `info` frame whose compute.unavailable_gpus has changed.
 */
export interface UnavailableGPU {
  pci_id: string;
  name: string;
  uuid: string;
  last_name: string;
  last_seen?: string | undefined;
  reason?: string | undefined;
  detail: string;
  recovery: string;
  bus?: GPUBusState | undefined;
}
